### ISSUE TITLE
关于 actions 构建

### ISSUE THREAD

**Issue by yinheli** [sing1ee/elasticsearch-jieba-plugin#101]
Hi @sing1ee 是否有考虑增加 actions 构建？我这边尝试做了一下 https://github.com/xinpianchang/elasticsearch-jieba-plugin/blob/xpc/7.17.x/.github/workflows/release.yaml

但是这个项目目前有些分支是独立维护的，你有什么建议吗？或者我可以来做相关的实现，提 PR

**Comment by sing1ee** [comment]
我没有研究过这个工具，但是感觉非常好。

我非常感谢，如果你可以提这个 PR 。

目前很多分支的原因，主要是版本的差别和 es 版本之间的差别。不知道如何才能自动化。感谢。
