### ISSUE TITLE
热更新词库

### ISSUE THREAD

**Issue by AlphaHi** [sing1ee/elasticsearch-jieba-plugin#11]
老大能不能给提供个思路，怎么加入热更新词库的功能呢，动态更新词典

**Comment by sing1ee** [comment]
WordDictionary 使用这个类的单例实例，调用loadUserDict方法即可加载自定义的词库。

**Comment by jiakechong1991** [comment]
如果是插件已经安装进了ES，我们怎么调用WordDictionary呢？能否像ik分词器那样，会周期的读取外部的API，这样我们只要控制外部的API就行了

**Comment by kewang** [comment]
請問這個功能有考慮內建在之後的版本上面嗎？

**Comment by sing1ee** [comment]
可以考虑下，可以提供一个接口，动态的加词。

Kewang <notifications@github.com> 于2019年4月17日周三 上午11:19写道：
