### ISSUE TITLE
6.0版本的用不了，索引的时候会报错

### ISSUE THREAD

**Issue by qinyuezhan** [sing1ee/elasticsearch-jieba-plugin#13]
startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=93,endOffset=96,lastStartOffset=94

还有：下面的例子中 synonyms/synonyms.txt 这个文件没有在打包文件里面，是没有上传？
{
  "settings": {
    "analysis": {
      "filter": {
        "jieba_stop": {
          "type":        "stop",
          "stopwords_path": "stopwords/stopwords.txt"
        },
        "jieba_synonym": {
          "type":        "synonym",
          "synonyms_path": "synonyms/synonyms.txt"
        }
      },
      "analyzer": {
        "my_ana": {
          "tokenizer": "jieba_index",
          "filter": [
            "lowercase",
            "jieba_stop",
            "jieba_synonym"
          ]
        }
      }
    }
  }
}

**Comment by sing1ee** [comment]
这个文件synonyms/synonyms.txt是es的配置

**Comment by sing1ee** [comment]
offset的bug，我处理一下。

**Comment by qinyuezhan** [comment]
谢答！这个文件synonyms/synonyms.txt是es的配置。在6.0.0版本 没有发现这个文件。
