### ISSUE TITLE
查询出错问题 

### ISSUE THREAD

**Issue by yyhjifeng** [sing1ee/elasticsearch-jieba-plugin#17]
按照README说明文档进行：
1: 下载  es : v6.0.0     jieba :  v6.0.1
2:  编译结巴并放到es插件下 
3:  拷贝停用词到指定目录下，并自己创建个synonyms.txt （找不到jieba对应的同义词文件）文件到指定目录下
4:  create index   成功  PUT http://localhost:9200/jieba_index 。。。

==========

5：test analyzer     这步出错

执行以下步骤
GET http://localhost:9200/jieba_index/_analyze?analyzer=my_ana&text=中国的伟大时代来临了，欢迎参观北京大学PKU

返回以下结果，请问下是什么原因导致的？

{
    "error": {
        "root_cause": [
            {
                "type": "parse_exception",
                "reason": "request body or source parameter is required"
            }
        ],
        "type": "parse_exception",
        "reason": "request body or source parameter is required"
    },
    "status": 400
}

如可以能否加你QQ 联系谢谢。

GET  http://localhost:9200/jieba_index 

response ：

{
    "jieba_index": {
        "aliases": {},
        "mappings": {},
        "settings": {
            "index": {
                "number_of_shards": "5",
                "provided_name": "jieba_index",
                "creation_date": "1532942171024",
                "analysis": {
                    "filter": {
                        "jieba_synonym": {
                            "type": "synonym",
                            "synonyms_path": "synonyms/synonyms.txt"
                        },
                        "jieba_stop": {
                            "type": "stop",
                            "stopwords_path": "stopwords/stopwords.txt"
                        }
                    },
                    "analyzer": {
                        "my_ana": {
                            "filter": [
                                "lowercase",
                                "jieba_stop",
                                "jieba_synonym"
                            ],
                            "tokenizer": "jieba_index"
                        }
                    }
                },
                "number_of_replicas": "1",
                "uuid": "1pDMeWYJQDmRAlD4P7KfJA",
                "version": {
                    "created": "6000099"
                }
            }
        }
    }
}

**Comment by sing1ee** [comment]
@yyhjifeng 
可以像我README一样，把真个demo的流程发一下么

**Comment by sing1ee** [comment]
@yyhjifeng 请问解决了么
平时不用QQ了~

**Comment by yyhjifeng** [comment]
这个问题解决了。是synonyms.txt 的编码问题 ，应该设置为UTF-8无BOM格式
