### ISSUE TITLE
test analyzer 报错 request body or source parameter is required

### ISSUE THREAD

**Issue by yuduanopen** [sing1ee/elasticsearch-jieba-plugin#19]
### **ES版本：elasticsearch-6.0.0 elasticsearch-jieba-plugin版本：elasticsearch-jieba-plugin-6.0.1 Windows**

- 下载并构建
      ` gradle pz`
- 复制文件
`将1中构建成功后build\distributions\elasticsearch-jieba-plugin-6.0.0.zip 复制到 elasticsearch-6.0.0\plugins解压并删除解压文件`
- 创建词库文件
`在elasticsearch-6.0.0\config 下创建stopwords/stopwords.txt 及 synonyms/synonyms.txt`
- 启动ES
`start elasticsearch`
- test analyzer
`在postman GET http://localhost:9200/jieba_index/_analyze?analyzer=my_ana&text=测试结巴分词看看结果出乎意料` 

- 错误结果：

> {
>     "error": {
>         "root_cause": [
>             {
>                 "type": "parse_exception",
>                 "reason": "request body or source parameter is required"
>             }
>         ],
>         "type": "parse_exception",
>         "reason": "request body or source parameter is required"
>     },
>     "status": 400
> }

**Comment by sing1ee** [comment]
my_ana 这个有定义么？

**Comment by yuduanopen** [comment]
定义了：
```
{
	"state": "open",
	"settings": {
		"index": {
			"number_of_shards": "5",
			"provided_name": "jieba_index",
			"creation_date": "1535711437745",
			"analysis": {
				"filter": {
					"jieba_synonym": {
						"type": "synonym",
						"synonyms_path": "synonyms/synonyms.txt"
					},
					"jieba_stop": {
						"type": "stop",
						"stopwords_path": "stopwords/stopwords.txt"
					}
				},
				"analyzer": {
					"my_ana": {
						"filter": [
							"lowercase",
							"jieba_stop",
							"jieba_synonym"
						],
						"tokenizer": "jieba_index"
					}
				}
			},
			"number_of_replicas": "1",
			"uuid": "0k68uIp_R2yUm3B6j5IMpg",
			"version": {
				"created": "6000099"
			}
		}
	},
	"mappings": {},
	"aliases": [],
	"primary_terms": {
		"0": 2,
		"1": 2,
		"2": 2,
		"3": 2,
		"4": 2
	},
	"in_sync_allocations": {
		"0": [
			"7tHtpGCgQ82G6ZL8eICMkg"
		],
		"1": [
			"S1sni7r1QR6TglW3cI5n9A"
		],
		"2": [
			"Qg03t8T6SGWZwI3k1ZE3Jg"
		],
		"3": [
			"ulZKKmGNQvyB0PeyV8hgKA"
		],
		"4": [
			"FEyFkUqIQbGyam0_zWsumw"
		]
	}
}
```
