### ISSUE TITLE
搜索句子时候 同义词失效

### ISSUE THREAD

**Issue by yyhjifeng** [sing1ee/elasticsearch-jieba-plugin#25]
按照readme 步骤 
一直到
test analyzer:
GET http://localhost:9200/jieba_index/_analyze?analyzer=my_ana&text=中国的伟大时代来临了，欢迎参观北京大学PKU

=====这一步得到的结果和readme是一样的，同义词能识别出来=======

但是到下一步：
search
POST http://localhost:9200/jieba_index/fulltext/_search
Request body:

{
    "query" : { "match" : { "content" : "pku" }},
    "highlight" : {
        "pre_tags" : ["<tag1>", "<tag2>"],
        "post_tags" : ["</tag1>", "</tag2>"],
        "fields" : {
            "content" : {}
        }
    }
}

得到的结果是不会出现同义词效果的。就是 《北京大学 》没有标注，只有pku 。？？？为什么？

**Comment by sing1ee** [comment]
搜索使用的分词是my_ana么?
