### ISSUE TITLE
自定义词未被命中

### ISSUE THREAD

**Issue by aforwardz** [sing1ee/elasticsearch-jieba-plugin#26]
自定义词：学区房
user.txt未添加”学区房“时，搜索时会命中”学区“和”房“这两个词
user.txt中添加 学区房 10(或者100/10000)  之后，未命中”学区房“这个词甚至没有”学区“和”房“这两个词
但是我测试分词器分出了”学区房“这个词
会是哪里有问题呢？

**Comment by sing1ee** [comment]
这个要确认，自定义字典是否加载了，如果加载了，会有日志打印。

另外，你这个场景可以用phrasequery来解决，设置合理的slop即可。

**Comment by aforwardz** [comment]
已经加载了，测试过analyzer，可以分出来，但是search的时候并没search自定义的词

我这里是需要在多个fields里检索，用的multi_match

**Comment by aforwardz** [comment]
自定义的停用词也未生效
我在config/stopwords/stopwords.txt 和plugin/jieba/dict/stopwords.txt中都设置了“什么”这个词
但search时并没有ignore“什么”这个词

**Comment by sing1ee** [comment]
你试一下其他的粉丝，看是否可行


Aforwardz <notifications@github.com> 于2018年10月10日周三 下午6:16写道：

**Comment by aforwardz** [comment]
@sing1ee 我发现一个问题，例如搜索“VC和PE有什么区别”，如果不加停用词，搜出来的结果主要是xx和yy有什么(区别/不同)，也就是并没有检索“VC”和“PE”这两个词，但是我加了停用词“有什么”之后，就可以搜索到“VC和PE的不同”，为什么es不会检索所有分出来的词？

**Comment by monarchwise** [comment]
添加了自定义词库需要重启ES集群吗，有没有远程词库配置，支持词库热部署

**Comment by sing1ee** [comment]
需要重启，可以开发一个这个功能

monarchwise <notifications@github.com> 于2018年11月7日周三 下午6:12写道：
