### ISSUE TITLE
使用6.4.1 release插件在elastic search6.4.0中使用，配置了同义词的index创建的时候报错

### ISSUE THREAD

**Issue by xueyanyun** [sing1ee/elasticsearch-jieba-plugin#29]
**创建索引**
```
DELETE /jieba_test
PUT /jieba_test
{
  "settings": {
    "analysis": {
      "filter": {
        "jieba_stop": {
          "type":        "stop",
          "stopwords_path": "stopwords/stopwords.txt"
        },
        "jieba_synonym": {
          "type":        "synonym",
          "synonyms_path": "synonyms/synonyms.txt"
        }
      },
      "analyzer": {
        "my_ana": {
          "tokenizer": "jieba_index",
          "filter": [
            "lowercase",
            "jieba_stop",
            "jieba_synonym"
          ]
        }
      }
    }
  }
}
```

**报错**
```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "failed to build synonyms"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "failed to build synonyms",
    "caused_by": {
      "type": "parse_exception",
      "reason": "Invalid synonym rule at line 1",
      "caused_by": {
        "type": "illegal_argument_exception",
        "reason": "term: 北京大学 analyzed to a token (北京大学) with position increment != 1 (got: 0)"
      }
    }
  },
  "status": 400
}
```
**近义词文件如下：**
北京大学,北大,pku
清华大学,清华,Tsinghua University

@sing1ee

**Comment by AlphaHi** [comment]
我用的5.4版本，词库里配置停用词和同义词都是不起作用的，只是没报错，搜的时候发现不起作用

**Comment by haowg** [comment]
我也遇到这个情况

**Comment by sing1ee** [comment]
我来测试一下。

**Comment by WSPTTH** [comment]
这个问题好像是因为 ES6.x 里面的同义词表要先过一遍tokenizer之后再进行处理 [doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-synonym-tokenfilter.html) 
可以把 "tokenizer": "jieba_index" 替换成 "jieba_search"，这样可以配置成功。因为 "jieba_index"同一个position会返回多个词，"jieba_search"是一个。

另外，页面的例子里可能有点问题，其中"content"字段没有配置索引，会导致检索时，分词无法生效。

完整的索引

```json
PUT /jieba_test
{
  "settings": {
    "analysis": {
      "filter": {
        "jieba_stop": {
          "type":        "stop",
          "stopwords_path": "stopwords/stopwords.txt"
        },
        "jieba_synonym": {
          "type":        "synonym",
          "synonyms_path": "synonyms/synonyms.txt"        
        }
      },
      "analyzer": {
        "my_ana": {
          "tokenizer": "jieba_search",
          "filter": [
            "lowercase",
            "jieba_stop",
            "jieba_synonym"
          ]
        }
      }
    }
  },
  "mappings": {
    "fulltext": {
      "properties": {
        "content": {
          "type": "text",
          "analyzer": "jieba_index",
          "search_analyzer": "my_ana"
        }
      }
    }
  }
}
```

**Comment by xueyanyun** [comment]
> 这个问题好像是因为 ES6.x 里面的同义词表要先过一遍tokenizer之后再进行处理 [doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-synonym-tokenfilter.html)
> 可以把 "tokenizer": "jieba_index" 替换成 "jieba_search"，这样可以配置成功。因为 "jieba_index"同一个position会返回多个词，"jieba_search"是一个。
> 
> 另外，页面的例子里可能有点问题，其中"content"字段没有配置索引，会导致检索时，分词无法生效。
> 
> 完整的索引
> 
> ```json
> PUT /jieba_test
> {
>   "settings": {
>     "analysis": {
>       "filter": {
>         "jieba_stop": {
>           "type":        "stop",
>           "stopwords_path": "stopwords/stopwords.txt"
>         },
>         "jieba_synonym": {
>           "type":        "synonym",
>           "synonyms_path": "synonyms/synonyms.txt"        
>         }
>       },
>       "analyzer": {
>         "my_ana": {
>           "tokenizer": "jieba_search",
>           "filter": [
>             "lowercase",
>             "jieba_stop",
>             "jieba_synonym"
>           ]
>         }
>       }
>     }
>   },
>   "mappings": {
>     "fulltext": {
>       "properties": {
>         "content": {
>           "type": "text",
>           "analyzer": "jieba_index",
>           "search_analyzer": "my_ana"
>         }
>       }
>     }
>   }
> }
> ```
