### ISSUE TITLE
PositionIncrement问题（Elasticsearch6.6.2 + jieba6.4.1）

### ISSUE THREAD

**Issue by DengGuangXue** [sing1ee/elasticsearch-jieba-plugin#35]
Elasticsearch6.6.2 ，我使用的是jieba 6.4.1插件
然后创建索引的时候，自定义analyzer如下所示：
              "jieba_syno_search": {
                    "type": "custom",
                    "tokenizer": "jieba_search",
                    "filter": [
                    	"jieba_stop",
                    	"my_synonym_filter"
                    ]
                },
发送请求后，就遇到下面这种错误：
{
    "error": {
        "root_cause": [
            {
                "type": "illegal_argument_exception",
                "reason": "failed to build synonyms"
            }
        ],
        "type": "illegal_argument_exception",
        "reason": "failed to build synonyms",
        "caused_by": {
            "type": "parse_exception",
            "reason": "Invalid synonym rule at line 1",
            "caused_by": {
                "type": "illegal_argument_exception",
                "reason": "term: 美国和伊拉克 analyzed to a token (伊拉克) with position increment != 1 (got: 2)"
            }
        }
    },
    "status": 400
}
还请指教，谢谢！

**Comment by sing1ee** [comment]
@DengGuangXue 我复现一下。

**Comment by DengGuangXue** [comment]
我也试了 Elasticsearch-v7.0.0 + jieba-v7.0.0 ，发现也有这样的问题

synonym.txt 中的内容如下所示：
美伊,美国和伊拉克
中韩,中国和韩国
中美,中国和美国
启航,起航
RMB => 人民币,RMB
西红柿,番茄
土豆,马铃薯 => 土豆
ES,Elasticsearch

若把  美伊,美国和伊拉克   改成   美伊,美国伊拉克   ，则会报错如下所示：
"reason": "term: 美国伊拉克 analyzed to a token (伊拉克) with position increment != 1 (got: 0)"

**Comment by sing1ee** [comment]
@DengGuangXue 我看下今天

**Comment by sing1ee** [comment]
POST http://localhost:9200/_analyze

```json
{
  "analyzer" : "jieba_index",
  "text" : "美国伊拉克"
}
```
结果：

```json
{
    "tokens": [
        {
            "token": "美国",
            "start_offset": 0,
            "end_offset": 2,
            "type": "word",
            "position": 0
        },
        {
            "token": "伊拉",
            "start_offset": 2,
            "end_offset": 4,
            "type": "word",
            "position": 1
        },
        {
            "token": "伊拉克",
            "start_offset": 2,
            "end_offset": 5,
            "type": "word",
            "position": 1
        },
        {
            "token": "拉克",
            "start_offset": 3,
            "end_offset": 5,
            "type": "word",
            "position": 1
        }
    ]
}
```

你换成jieba_search试试

**Comment by DengGuangXue** [comment]
> 
> 你换成jieba_search试试
>

我试了一下，把 jieba_index 那部分的 analyzer 去掉，只留下 jieba_search 的 ，
再把 美伊,美国和伊拉克 改成 美伊,美国伊拉克 ，然后创建索引就没问题了

后面，我又对 美伊,美国伊拉克  做了几种修改，再创建索引，相应结果如下所示：
1、美伊,美国与伊拉克        --- fail
2、美伊,美国伊拉克伊朗    --- success
3、伊美,伊拉克加美国        --- success

对于 jieba_search ,  我发现只要同义词中不含有停用词，就能够成功创建索引
希望后面的版本能够解决包含停用词报错的问题，这样用户体验更好
或者在使用说明那里说清楚也行

而对于 jieba_index , 无论怎么修改synonym.txt ，都不能和synonym_filter一起用
个人看法：如果只是做搜索平台的话，这一点是没有什么问题的

**Comment by sing1ee** [comment]
@DengGuangXue 多谢。我做一下改进，分词这块，我在做一个新的。适合检索和索引的。

**Comment by yuyanguo2018** [comment]
> > 你换成jieba_search试试
> 
> 我试了一下，把 jieba_index 那部分的 analyzer 去掉，只留下 jieba_search 的 ，
> 再把 美伊,美国和伊拉克 改成 美伊,美国伊拉克 ，然后创建索引就没问题了
> 
> 后面，我又对 美伊,美国伊拉克 做了几种修改，再创建索引，相应结果如下所示：
> 1、美伊,美国与伊拉克 --- fail
> 2、美伊,美国伊拉克伊朗 --- success
> 3、伊美,伊拉克加美国 --- success
> 
> 对于 jieba_search , 我发现只要同义词中不含有停用词，就能够成功创建索引
> 希望后面的版本能够解决包含停用词报错的问题，这样用户体验更好
> 或者在使用说明那里说清楚也行
> 
> 而对于 jieba_index , 无论怎么修改synonym.txt ，都不能和synonym_filter一起用
> 个人看法：如果只是做搜索平台的话，这一点是没有什么问题的

你好，请教一下，我的把analyzer无论换成是jieba_search还是jieba_index都不成功是什么原因啊
![image](https://user-images.githubusercontent.com/39588867/57595128-f1cedc00-7575-11e9-9516-a911cc47780a.png)
![image](https://user-images.githubusercontent.com/39588867/57595152-027f5200-7576-11e9-8005-ecbc5dea73d7.png)

**Comment by DefinitionBeyond** [comment]
你好，对于自定义词词典，它是启动就会加载的吗。为何就是user.dict中存在的小清新一词，也被分词了
![image](https://user-images.githubusercontent.com/31152889/62991223-548b8880-be81-11e9-9d4c-e729fd162c88.png)

![image](https://user-images.githubusercontent.com/31152889/62991174-28700780-be81-11e9-9c70-6de485853d9e.png)
![image](https://user-images.githubusercontent.com/31152889/62991237-64a36800-be81-11e9-8050-4537bb3bcc55.png)

**Comment by sing1ee** [comment]
@DefinitionBeyond 我做了测试
ES 7.0.0。***小清新***没有被分词。

**Comment by DefinitionBeyond** [comment]
你好，我的环境也是es7.0.0和jieba_plugin7.0.0，那请问一下您对于自定义分词的settings是怎样的，看是不是我这方面整错了

**Comment by sing1ee** [comment]
没做什么设置，只修改了 user.dict

DefinitionBeyond <notifications@github.com> 于2019年8月14日周三 下午3:00写道：

**Comment by DengGuangXue** [comment]
@DefinitionBeyond  你有没有加了其他词典？不然“小清新”是不会被分词的

**Comment by DefinitionBeyond** [comment]
@DengGuangXue  没有，现在只是添加了同义词文件，user.dict没有添加词，dic下目前是默认的sougou.dict和user.dict。然后测试过程如我截图所示

**Comment by yiwei-sb** [comment]
> > 你换成jieba_search试试
> 
> 我试了一下，把 jieba_index 那部分的 analyzer 去掉，只留下 jieba_search 的 ，
> 再把 美伊,美国和伊拉克 改成 美伊,美国伊拉克 ，然后创建索引就没问题了
> 
> 后面，我又对 美伊,美国伊拉克 做了几种修改，再创建索引，相应结果如下所示：
> 1、美伊,美国与伊拉克 --- fail
> 2、美伊,美国伊拉克伊朗 --- success
> 3、伊美,伊拉克加美国 --- success
> 
> 对于 jieba_search , 我发现只要同义词中不含有停用词，就能够成功创建索引
> 希望后面的版本能够解决包含停用词报错的问题，这样用户体验更好
> 或者在使用说明那里说清楚也行
> 
> 而对于 jieba_index , 无论怎么修改synonym.txt ，都不能和synonym_filter一起用
> 个人看法：如果只是做搜索平台的话，这一点是没有什么问题的

@DengGuangXue  翻個舊文， Lucene 目前對於同時使用「同義詞」和「停用詞」的支援度很差，不只是中文 jieba 的問題。如果 analyzer 先放停用詞 filter 再放同義詞 filter 就會碰到你敘述的問題（如果同義詞內含有停用詞因而被刪除)，但是先放同義詞 filter 再放停用詞 filter 在 ES6 / Lucene 7 又會有另一種問題。詳見
* https://sease.io/2018/07/combining-synonyms-and-stopwords.html
* https://github.com/elastic/elasticsearch/issues/28838
