### ISSUE TITLE
Add stopwords without restart elasticsearch

### ISSUE THREAD

**Issue by feiyangzhang** [sing1ee/elasticsearch-jieba-plugin#36]
How to add stopwords to config/stopwords.txt without restarting es

**Comment by wuqinlong** [comment]
我也有个类似的问题，我想动态的去更新词库。

简单看一下源码，huban的jieba代码里有相应的接口，但是作者这个es插件里并没有，估计得自己动手了

**Comment by sing1ee** [comment]
send me a new pull request? @feiyangzhang @wuqinlong

**Comment by sing1ee** [comment]
@wuqinlong 我想可以这样，在构造query的时候，先过一遍停用词，再构造。是否会好些。
