### ISSUE TITLE
6.7.2的elasticsearch怎么使用适合版本的插件

### ISSUE THREAD

**Issue by ydzhao-reyes** [sing1ee/elasticsearch-jieba-plugin#37]
我用6.7.2的elasticsearch使用6.4.1的jieba会报错如下，请问怎么解决呢

**Comment by ydzhao-reyes** [comment]
![image](https://user-images.githubusercontent.com/42952460/58074610-44447400-7bd8-11e9-8268-7c4788d09c08.png)

**Comment by sing1ee** [comment]
源代码里该改一下版本，然后build
