### ISSUE TITLE
关于Tokenizer Filter

### ISSUE THREAD

**Issue by Hawaii-ol** [sing1ee/elasticsearch-jieba-plugin#38]
我看huaban的文档中有“全角转半角、大写转小写、字符分词”的tokenizer filter，但是没有找到使用方法，也不知道这些filter的名称，希望指点一下

**Comment by sing1ee** [comment]
这个我这边支持一下。

Hawaii-ol <notifications@github.com> 于2019年6月3日周一 下午12:22写道：

**Comment by sing1ee** [comment]
@Hawaii-ol 并没有找到这些Tokenizer filter。这个定义，可以参考ES的语法进行组合。
