### ISSUE TITLE
你好,我这里用的是ES的7.0.0版本,按照你这里的过程安装jieba插件,一切顺利。但是重启ES后，并没有将plugins中的jieba插件加载进来。请问怎么解决？

### ISSUE THREAD

**Issue by BlueSkyBubble** [sing1ee/elasticsearch-jieba-plugin#39]

**Comment by BlueSkyBubble** [comment]
##以下是plugin-descriptor.properties文件中的内容，看了一下也不是版本的问题
#
# 'description': simple summary of the plugin
description=A jieba analysis of plugins for Elasticsearch
#
# 'version': plugin's version
version=7.0.0
#
# 'name': the plugin name
name=jieba
#
# 'classname': the name of the class to load, fully-qualified.
classname=org.elasticsearch.plugin.analysis.jieba.AnalysisJiebaPlugin
#
# 'java.version' version of java the code is built against
java.version=1.8
#
# 'elasticsearch.version' version of elasticsearch compiled against
elasticsearch.version=7.0.0

**Comment by sing1ee** [comment]
把解压出来的文件，都放到jieba目录里。
plugins/jieba，这样的结构。
