### ISSUE TITLE
如何根据自定义词典，从文本中提取词典中的关键词? 

### ISSUE THREAD

**Issue by sj8354661** [sing1ee/elasticsearch-jieba-plugin#41]
需求：
如何根据自定义词典，从文本中提取词典中的关键词。

设想三种方案：
1、输入文本，获取结巴分词结果，编写一套代码根据分词结果对比自定义词典，输出同时包含在文本中和词典中的词。
2、输入文本，编写一套代码，逐个查询词典中的词是否在文本中出现，输出同时包含在文本中和词典中的词。
3、利用结巴词性标注的功能，在自定义词典中，将自定义词全部标注为某一特殊词性，利用结巴根据词性提取关键词功能，输入文本，提取指定词性的关键词。
4、利用结巴自定义词典功能，分词完全根据指定的自定义词典进行分词，输入文本，调用指定词典，输出分词结果。
5、利用结巴权重功能，输出分词结果中将指定自定义词典中的词的权重调大，其他词权重调低，输出分词结果后，截取权重靠前的几个词。

问题：
哪种方案可以实现需求？
结巴有没有直接根据算定义词典提取关键词的功能？

因为没有看到可以直接实现类似这样需求的资料，所以在此提问，请不吝赐教！

如果您了解这方面技术，请提供一下思路，如果能提供一下教程学习地址，或者写点参考代码就更好了。谢谢，不胜感激！

**Comment by sing1ee** [comment]
我在jieba里贡献了一个TextRank算法的实现，可以用来做关键词的抽取。

sj8354661 <notifications@github.com> 于2019年8月22日周四 下午2:03写道：

**Comment by sj8354661** [comment]
请问相关代码在哪里？我对github不熟悉不知道怎么找。

**Comment by sj8354661** [comment]
add a simple implementation of textrank · fxsjy/jieba@6eb9f61 
https://github.com/fxsjy/jieba/commit/6eb9f6149c12c442cd8caf9ce5fa48b405abec01

请问是上面这个页面么？代码是PY的，我只会PHP，在PHP版本里没找到这部分的代码。

**Comment by sj8354661** [comment]
使用elasticsearch-jieba-plugin，可以调用textrank方法么？如果可以，怎样使用？

**Comment by sing1ee** [comment]
@sj8354661 不可以，jieba分词python版本中实现了。java版本在这里：[textrank-java](https://github.com/sing1ee/textrank-java)
