### ISSUE TITLE
能不能对应一下Elasticsearch7.3版本？谢谢

### ISSUE THREAD

**Issue by zhoutingze** [sing1ee/elasticsearch-jieba-plugin#42]
Plugin [jieba] was built for Elasticsearch version 7.0.0 but version 7.3.0 is running

**Comment by zhoutingze** [comment]
能帮帮我吗

**Comment by sing1ee** [comment]
OK，实际上改一下配置文件，重新打包就可以了。我来操作一下。

zhoutingze <notifications@github.com> 于2019年8月27日周二 下午1:49写道：

**Comment by sing1ee** [comment]
```shell
git checkout 7.3.0
./gradlew pz
```
