### ISSUE TITLE
加载自定义的同义词出现错误如下，请问怎么解决

### ISSUE THREAD

**Issue by xiaonian0430** [sing1ee/elasticsearch-jieba-plugin#43]
{'error': {'root_cause': [{'type': 'illegal_argument_exception', 'reason': 'failed to build synonyms'}], 'type': 'illegal_argument_exception', 'reason': 'failed to build synonyms', 'caused_by': {'type': 'parse_exception', 'reason': 'Invalid synonym rule at line 1', 'caused_by': {'type': 'illegal_argument_exception', 'reason': 'term: 北京大学 analyzed to a token (北京大学) with position increment != 1 (got: 0)'}}}, 'status': 400}

**Comment by GCHWhy** [comment]
我的版本是7.3.0，加载同义词典刚开始失败，参考#29个问题解决了。

> 把 "tokenizer": "jieba_index" 替换成 "jieba_search"

**Comment by sing1ee** [comment]
赞

GCHWhy <notifications@github.com> 于2019年11月21日周四 上午10:30写道：

**Comment by xiaonian0430** [comment]
好的，谢谢问题解决了。
把 "tokenizer": "jieba_index" 替换成 "jieba_search"
