### ISSUE TITLE
求适配最新的ES版本（7.4.2）

### ISSUE THREAD

**Issue by Wesley-GONG** [sing1ee/elasticsearch-jieba-plugin#44]
如题，IK完全靠分词词库，有点吃不消啊

**Comment by sing1ee** [comment]
@Wesley-GONG 周末搞一下。

**Comment by rwei1218** [comment]
同求支持7.4.2

**Comment by sing1ee** [comment]
https://github.com/sing1ee/elasticsearch-jieba-plugin/tree/7.4.2 

@Wesley-GONG @rwei1218 7.4.2
