### ISSUE TITLE
期待适配 ES 最新版本（7.6.0）

### ISSUE THREAD

**Issue by cikai** [sing1ee/elasticsearch-jieba-plugin#48]
一直在使用插件6.4.0版本，近期计划升级ES版本到7.6.0，期待早日适配！
@sing1ee  作者您好，近期是否有计划更新呢，谢谢

**Comment by sing1ee** [comment]
@cikai 好，少等

**Comment by cjymz886** [comment]
@sing1ee 作者您好，es7.2.0能用吗？
