### ISSUE TITLE
是否支持热更新自定义词典

### ISSUE THREAD

**Issue by Old-Su** [sing1ee/elasticsearch-jieba-plugin#52]
请问作者, 当前jieba插件是否支持热更新词典呢? 
支持的话有没有具体配置的文档?

**Comment by sing1ee** [comment]
·更新词典，需要重建索引。所以，目前还不支持。

苏 <notifications@github.com> 于2020年4月21日周二 下午7:31写道：

**Comment by Old-Su** [comment]
我的意思是自定义词典可在不重启es服务的情况下进行更新, 重建索引肯定是要做的.

**Comment by sing1ee** [comment]
@Old-Su 好，支持一下，预计五一。

**Comment by Old-Su** [comment]
多谢大佬.

**Comment by febmark** [comment]
希望早日支持热更新
