### ISSUE TITLE
不支持es6.3么

### ISSUE THREAD

**Issue by zjcnew** [sing1ee/elasticsearch-jieba-plugin#53]
elasticsearch6.3.0用哪个版本，还是说不支持？

**Comment by sing1ee** [comment]
@zjcnew 可以简单修改一下版本，然后直接打包就可以了。

**Comment by sing1ee** [comment]
@zjcnew 看这里：
https://github.com/sing1ee/elasticsearch-jieba-plugin/blob/master/custom_plugin_version.md

**Comment by vissible** [comment]
基于master打包吗？
