### ISSUE TITLE
jieba tokenizer 問題

### ISSUE THREAD

**Issue by nowitzki0205** [sing1ee/elasticsearch-jieba-plugin#55]
我加入了 16:9 這組字串在dic裡，但仍然會被切開，請問有什麼地方可以設定遇到 ':' 符號不分詞嗎?

**Comment by sing1ee** [comment]
@nowitzki0205 這應該是jieba分詞的算法，如果要改這個，需要從結巴這一層開始改。有什麼別的方法麼？
