### ISSUE TITLE
es 6.4.3 使用jieba不能挂载外部词典吗，在6.4版本的说明中没有找到

### ISSUE THREAD

**Issue by FFFro** [sing1ee/elasticsearch-jieba-plugin#57]
我将最新版的代码中的外挂词典部分迁移过来有影响么

**Comment by sing1ee** [comment]
@FFFro 这个版本，可以自己定制一下。重点看这两个链接：
### 简单的修改，即可适配不同版本的ES

[戳这里](custom_plugin_version.md)

### 支持动态添加字典，ES不需要重启

[戳这里](update_dict_online.md)

**Comment by FFFro** [comment]
> @FFFro 这个版本，可以自己定制一下。重点看这两个链接：
> 
> ### 简单的修改，即可适配不同版本的ES
> [戳这里](https://github.com/sing1ee/elasticsearch-jieba-plugin/blob/master/custom_plugin_version.md)
> 
> ### 支持动态添加字典，ES不需要重启
> [戳这里](https://github.com/sing1ee/elasticsearch-jieba-plugin/blob/master/update_dict_online.md)

目前，我们已经对现在使用的jieba插件进行了一部分调整，如果需要通过这种调整就要把目前的修改同步到有动态添加字典的版本中，那应该选哪种方法呢

**Comment by sing1ee** [comment]
@FFFro 可以直接把我的代码合并。或者如果是很好的功能，可以提一个pr

**Comment by FFFro** [comment]
@sing1ee 好的，感谢
