### ISSUE TITLE
jieba-analysis is not declared in the descriptor for project

### ISSUE THREAD

**Issue by jrayu** [sing1ee/elasticsearch-jieba-plugin#59]
gradlew最新版本7.7.1报错

~/tarballs/elasticsearch-jieba-plugin-7.7.1$ ./gradlew clean pz

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':pz'.
> Could not resolve all task dependencies for configuration ':distJars'.
   > Could not resolve project :jieba-analysis.
     Required by:
         project :
      > Project : declares a dependency from configuration 'compile' to configuration 'default' which is not declared in the descriptor for project :jieba-analysis.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 865ms

目录结构就是tar解压，检查了一下是有Jieba-analysis这个文件的，虽然里面是空的

**Comment by sing1ee** [comment]
执行如下命令：
```shell
git clone https://github.com/sing1ee/elasticsearch-jieba-plugin.git --recursive
./gradlew clean pz
```
注意：```--recursive```
