### ISSUE TITLE
为什么安装最新版7.7.0会有错误？

### ISSUE THREAD

**Issue by yoyomuc** [sing1ee/elasticsearch-jieba-plugin#60]

**Comment by sing1ee** [comment]
@yoyomuc 什么错误

**Comment by yoyomuc** [comment]
<img width="729" alt="Bildschirmfoto 2020-06-24 um 13 10 50" src="https://user-images.githubusercontent.com/67334898/85545498-49b29000-b61c-11ea-870f-494b1a8ab544.png">

**Comment by yoyomuc** [comment]
<img width="697" alt="Bildschirmfoto 2020-06-24 um 13 11 20" src="https://user-images.githubusercontent.com/67334898/85545617-66e75e80-b61c-11ea-88c0-ccfc566a19f8.png">

**Comment by sing1ee** [comment]
你通过命令行打包，之后再使用。如下链接

https://github.com/sing1ee/elasticsearch-jieba-plugin/blob/master/custom_plugin_version.md
