### ISSUE TITLE
用户词库无法热加载，只有重启es才生效

### ISSUE THREAD

**Issue by lizheng0329** [sing1ee/elasticsearch-jieba-plugin#61]
添加新的dict词库文件后，只有重启es后才能加载新添加的词库。ES版本：6.4.0  ，代码使用master分支，且配置文件已经改为6.4.0版本。

**Comment by sing1ee** [comment]
https://github.com/sing1ee/elasticsearch-jieba-plugin/blob/master/update_dict_online.md
是否按照上面做了配置

**Comment by lizheng0329** [comment]
是按照上面链接做的配置，不过问题已经找到了。master分支的代码，里面引用的jieba-analysis，应该是本地下载好的jieba-analysis工程源码吧？如果引用jieba-analysis项目最新的1.0.2版本，里面加载用户词典的源码为 if (loadedPath.contains(abspath)){return;}  也就是说，第一次扫描的词典路径，在第二次加载时，直接跳出，不再扫描该路径下的文件，所以词典导致无法热加载。

**Comment by lizheng0329** [comment]
是按照上面链接做的配置，不过问题已经找到了。master分支的代码，里面引用的jieba-analysis，应该是本地下载好的jieba-analysis工程源码吧？如果引用jieba-analysis项目最新的1.0.2版本，里面加载用户词典的源码为 if (loadedPath.contains(abspath)){return;} 也就是说，第一次扫描的词典路径，在第二次加载时，直接跳出，不再扫描该路径下的文件，所以词典导致无法热加载。

**Comment by sing1ee** [comment]
我修改了jieba-analysis，要使用git submodule的方式依赖。
