### ISSUE TITLE
請問打包時出現Could not resolve project :jieba-analysis訊息，該如何解決

### ISSUE THREAD

**Issue by antonov0318** [sing1ee/elasticsearch-jieba-plugin#63]
您好
請問打包時遇到如下的錯誤訊息
該如何解決呢，謝謝

>FAILURE: Build failed with an exception.

>* What went wrong:
>Could not determine the dependencies of task ':pz'.
> Could not resolve all task dependencies for configuration ':distJars'.
   > Could not resolve project :jieba-analysis.
     Required by:
         project :
      > Project : declares a dependency from configuration 'compile' to configuration 'default' which is not declared in the >descriptor for project :jieba-analysis.

>* Try:
>Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

>* Get more help at https://help.gradle.org

>BUILD FAILED in 2s

**Comment by hezhiqiang** [comment]
我也碰到这个问题，你是怎么解决的？
