### ISSUE TITLE
./gradlew clean pz  失败

### ISSUE THREAD

**Issue by codingwangfeng** [sing1ee/elasticsearch-jieba-plugin#65]
./gradlew clean pz 

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':pz'.
> Could not resolve all task dependencies for configuration ':distJars'.
   > Could not resolve project :jieba-analysis.
     Required by:
         project :
      > Project : declares a dependency from configuration 'compile' to configuration 'default' which is not declared in the descriptor for project :jieba-analysis.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

**Comment by teaGod-s** [comment]
+1

**Comment by sing1ee** [comment]
git pull origin master --recursive

**Comment by tsaiian** [comment]
+1

**Comment by tsaiian** [comment]
The error seems to only appear in `v7.7.0`
I can install `v7.4.2` without this error.

**Comment by bjelements** [comment]
git clone https://github.com/sing1ee/elasticsearch-jieba-plugin.git --recursive
正克隆到 'elasticsearch-jieba-plugin'...
remote: Enumerating objects: 151, done.
remote: Counting objects: 100% (151/151), done.
remote: Compressing objects: 100% (85/85), done.
remote: Total 616 (delta 64), reused 113 (delta 40), pack-reused 465
接收对象中: 100% (616/616), 1.41 MiB | 518.00 KiB/s, done.
处理 delta 中: 100% (274/274), done.
子模组 'jieba-analysis' (git@github.com:sing1ee/jieba-analysis.git) 已为路径 'jieba-analysis' 注册
正克隆到 'jieba-analysis'...
Warning: Permanently added the RSA host key for IP address '52.74.223.119' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by sing1ee** [comment]
@bjelements 把自己的ssh pub key，加到github上

**Comment by bjelements** [comment]
master 分支出现的错误
C:\Users\hp\Desktop\elasticsearch-jieba-plugin>gradlew clean pz
> Task :jieba-analysis:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jieba-analysis:compileJava'.
> Could not resolve all files for configuration ':jieba-analysis:compileClasspath'.
   > Could not resolve org.apache.commons:commons-lang3:3.3.1.
     Required by:
         project :jieba-analysis
      > Could not resolve org.apache.commons:commons-lang3:3.3.1.
         > Could not get resource 'http://repo.maven.apache.org/maven2/org/apache/commons/commons-lang3/3.3.1/commons-lang3-3.3.1.pom'.
            > Could not HEAD 'http://repo.maven.apache.org/maven2/org/apache/commons/commons-lang3/3.3.1/commons-lang3-3.3.1.pom'. Received status code 501 from server: HTTPS Required

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
3 actionable tasks: 1 executed, 2 up-to-date

**Comment by yingzhige118** [comment]
请问支持远程自定义同义词和专有名词吗？http路径

**Comment by Jackeriss** [comment]
@bjelements 全局搜索`http://repo.maven.apache.org/maven2`，替换为`https://repo.maven.apache.org/maven2`即可。

**Comment by newman1234** [comment]
any updates? thx

**Comment by zjcnew** [comment]
Starting a Gradle Daemon (subsequent builds will be faster)
> Task :jieba-analysis:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jieba-analysis:compileJava'.
> Could not resolve all files for configuration ':jieba-analysis:compileClasspath'.
   > Could not resolve org.apache.commons:commons-lang3:3.3.1.
     Required by:
         project :jieba-analysis
      > Could not resolve org.apache.commons:commons-lang3:3.3.1.
         > Could not get resource 'http://repo.maven.apache.org/maven2/org/apache/commons/commons-lang3/3.3.1/commons-lang3-3.3.1.pom'.
            > Could not HEAD 'http://repo.maven.apache.org/maven2/org/apache/commons/commons-lang3/3.3.1/commons-lang3-3.3.1.pom'. Received status code 501 from server: HTTPS Required

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 12s
1 actionable task: 1 executed

**Comment by sing1ee** [comment]
> 请问支持远程自定义同义词和专有名词吗？http路径

这个目前不支持，可以下载下来。

**Comment by RyanWHH** [comment]
下载 jieba-analysis项目源码解压到 jieba-analysis 目录下，修改jieba-analysis 目录下的build.gradle指定国内maven镜像，最后打包即可 
![image](https://user-images.githubusercontent.com/24239352/114523458-e2cb9980-9c76-11eb-9156-b28a11dde853.png)

```
plugins {
    id 'java'
    id 'maven-publish'
}

repositories {
    mavenLocal()
   //修改
    maven { url "http://maven.aliyun.com/nexus/content/groups/public/" }
}
```

**Comment by sing1ee** [comment]
两个方法
1. git clone 的时候，带参数--recursive
2. git clone 之后，git submodule init，然后，git submodule update。源码就全部下载下来了

**Comment by wilson55** [comment]
> master 分支出现的错误 C:\Users\hp\Desktop\elasticsearch-jieba-plugin>gradlew clean pz
> 
> > Task :jieba-analysis:compileJava FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':jieba-analysis:compileJava'.
> 
> > Could not resolve all files for configuration ':jieba-analysis:compileClasspath'.
> > Could not resolve org.apache.commons:commons-lang3:3.3.1.
> > Required by:
> > project :jieba-analysis
> > > Could not resolve org.apache.commons:commons-lang3:3.3.1.
> > > Could not get resource 'http://repo.maven.apache.org/maven2/org/apache/commons/commons-lang3/3.3.1/commons-lang3-3.3.1.pom'.
> > > Could not HEAD 'http://repo.maven.apache.org/maven2/org/apache/commons/commons-lang3/3.3.1/commons-lang3-3.3.1.pom'. Received status code 501 from server: HTTPS Required
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 7s 3 actionable tasks: 1 executed, 2 up-to-date

將 elasticsearch-jieba-plugin/jieba-analysis 的 build.grade maven {
url = 'https://repo.maven.apache.org/maven2'
} 即可

**Comment by sing1ee** [comment]
👍

wilson55 ***@***.***> 于2022年10月14日周五 12:36写道：
