### ISSUE TITLE
新增词到词库无效，需要重启ES才生效

### ISSUE THREAD

**Issue by Limaoda** [sing1ee/elasticsearch-jieba-plugin#74]
新增词到词库无效，需要重启ES才生效？？？

**Comment by sing1ee** [comment]
不用的，会有自动的加载，你看看代码

Mao ***@***.***> 于2021年6月5日周六 下午2:11写道：

**Comment by ytk929** [comment]
看代码是在7.7.0这个分支之后才加入的自动加载，老的版本没有，可以自己build一下

**Comment by sing1ee** [comment]
是的。

ytk929 ***@***.***> 于2021年9月7日周二 下午6:46写道：

**Comment by Limaoda** [comment]
> 看代码是在7.7.0这个分支之后才加入的自动加载，老的版本没有，可以自己构建一下

7.6.2需要怎么处理下才能自动加载？？

**Comment by ytk929** [comment]
> > 看代码是在7.7.0这个分支之后才加入的自动加载，老的版本没有，可以自己构建一下
> 
> 7.6.2需要怎么处理下才能自动加载？？

我是这样操作的
1. 克隆此项目 切换到7.7.1 tag
2. 修改.gitmodules中git子模块jieba-analysis的url (在作者的仓库中)，并执行`git submodule sync`
3. 参考作者提供的版本适配说明[适配不同版本ES的jieba分词插件](https://github.com/sing1ee/elasticsearch-jieba-plugin/blob/master/custom_plugin_version.md) 我本地打包使用的是`gradle pz`
