### ISSUE TITLE
gradle pz:Could not get unknown property 'runtime' for configuration ':distJars' of type org.gradle.api.internal.artifacts.configurations.DefaultConfiguration

### ISSUE THREAD

**Issue by Lubamabi** [sing1ee/elasticsearch-jieba-plugin#75]
it's so hard to build the jar and use this project,hope this can be improved.
my steps
1 install gradle
2 git clone according to  https://github.com/sing1ee/elasticsearch-jieba-plugin/issues/65
3 gradlews -- no this command on windows
4 gradlew  cannot find org.gradle.wrapper.GradleWrapperMain ,need to find gradle-wrapper.jar
5 gradle pz ,also get  error like the image shows
6 help me

![image](https://user-images.githubusercontent.com/48797643/124379182-0dfadd80-dce8-11eb-8f69-d02c64afffb5.png)

**Comment by Lubamabi** [comment]
是我不太会有gradle吗？各种报错无法打包，希望能把相关东西在wiki'上写明白些，缺的东西在项目中补充上。

**Comment by Lubamabi** [comment]
finally resolved! please note the version of gradle on the wiki
原来下载的最新的gradle 7.1.7不行，下了个老版本 5.6.2解决,太难了....

**Comment by Lubamabi** [comment]
但是解决了上面的问题之后，es version换成6.4.2 或者 6.4.1就出现以下问题：
\elasticsearch-jieba-plugin\src\main\java\org\elasticsearch\index\analysis\JiebaTokenizerFactory.java:18: 错误: 不兼容的类型: Settings无法转换为String
    super(indexSettings, settings, TokenizerName);

**Comment by glorytheksy** [comment]
说的太对了，readme都没说明白，各种不能打包

**Comment by wilson55** [comment]
若使用 ./gradlew clear pz 顯示下列的錯誤
[ "Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain"] 表示在 elasticsearch-jieba-plugin/gradle/wapper/ 中少了一個檔:gradle-wrapper.jar檔，可以用gradle wrapper --gradle-version 5.6.2 --info 來產生

**Comment by skyemin** [comment]
> 但是解决了上面的问题之后，es version换成6.4.2 或者 6.4.1就出现以下问题： \elasticsearch-jieba-plugin\src\main\java\org\elasticsearch\index\analysis\JiebaTokenizerFactory.java:18: 错误: 不兼容的类型: Settings无法转换为String super(indexSettings, settings, TokenizerName);



> 但是解决了上面的问题之后，es version换成6.4.2 或者 6.4.1就出现以下问题： \elasticsearch-jieba-plugin\src\main\java\org\elasticsearch\index\analysis\JiebaTokenizerFactory.java:18: 错误: 不兼容的类型: Settings无法转换为String super(indexSettings, settings, TokenizerName);

老哥你解决了吗?我也遇到了

**Comment by sing1ee** [comment]
java 和 和elasticsearch都升级了版本，我来更新下程序，今天发布。

**Comment by shiny** [comment]
为什么不直接发个 release 呢

**Comment by sing1ee** [comment]
> 

es版本之间并不兼容的~需要更多测试哪些版本可以用哪个，但你这个是一个好的建议。
