### ISSUE TITLE
plugin-descriptor.properties version can not update 

### ISSUE THREAD

**Issue by zhishengzhang** [sing1ee/elasticsearch-jieba-plugin#84]
1 build.gradle info
`/*
 * This build file was auto generated by running the Gradle 'init' task
 * by 'zhangcheng' at '17-1-17 下午8:18' with Gradle 2.10
 *
 * This generated file contains a commented-out sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * user guide available at https://docs.gradle.org/2.10/userguide/tutorial_java_projects.html
 */

group 'org.elasticsearch'
version = '7.5.0' // 适配不通版本的ES，可以修改这里。
apply plugin: 'java'
apply plugin: 'idea'

sourceCompatibility = "1.8"
targetCompatibility = "1.8"
[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'

repositories {
    maven { url "https://maven.aliyun.com/nexus/content/groups/public/" }
    jcenter()
}
sourceSets {
    main {
        java {
            srcDir "src/main/java"
        }
        resources {
            srcDir "src/main/resources"
            srcDir "src/main/assemblies"
            srcDir "src/main/dic"
                include "**/*"
        }
    }
}

task initSourceFolders {
	sourceSets*.java.srcDirs*.each { it.mkdirs() }
	sourceSets*.resources.srcDirs*.each { it.mkdirs() }
}

configurations {
    wagon
    distJars {
        extendsFrom runtimeOnly
        exclude group: 'org.elasticsearch'
        exclude group: 'lucene-core'
        exclude group: 'org.apache.logging.log4j'
        exclude group: 'lucene-analyzers-common'
        exclude group: 'org.apache.commons'
    }
}

dependencies {
    implementation project(":jieba-analysis")
    implementation 'org.elasticsearch:elasticsearch:7.5.0' // 适配不通版本的ES，可以修改这里。
    implementation 'org.apache.logging.log4j:log4j-api:2.7'
    implementation 'org.apache.logging.log4j:log4j-core:2.7'
    testImplementation 'junit:junit:4.12'
}

tasks.named("processResources") {
    duplicatesStrategy = 'include'
}

task pz(type: Zip, dependsOn: [':jar']) {
    into("jieba") {
        from configurations.distJars
        from 'build/libs'
        from 'jieba-analysis/build/libs'
        from 'build/resources/main/plugin.xml'
        from 'build/resources/main/plugin-descriptor.properties'
    }
    from('build/resources/main/') {
        include '**.dict'
        include '**.txt'
        into ('jieba/dic')
    }
}
`

2  ./gradlew pz
plugin-descriptor.properties canot update 
`

description=A jieba analysis of plugins for Elasticsearch

version=7.7.0

name=jieba

classname=org.elasticsearch.plugin.analysis.jieba.AnalysisJiebaPlugin

java.version=8

elasticsearch.version=7.7.0

`

**Comment by sing1ee** [comment]
我更新了，7.17.x和8.4.1分支，可以试试
