### ISSUE TITLE
目前这个分中插件支持7.10.0的ES版本不？

### ISSUE THREAD

**Issue by m5jun** [sing1ee/elasticsearch-jieba-plugin#88]

**Comment by sing1ee** [comment]
可以直接更新版本，然后编译打包就可以了

2022-06-15 11:22 GMT+08:00, 高级研究员 ***@***.***>:

**Comment by liqunlin** [comment]
jieba分词插件支持ES7.9.3版本吗？更新版本号为7.9.3 编译打包安装后，发现分词效果差异很大：
![image](https://user-images.githubusercontent.com/11884077/184277417-160d7e9d-7af5-4e3b-9415-881e7f84cc6b.png)
![image](https://user-images.githubusercontent.com/11884077/184277442-cd0bc02a-c217-4583-ac5e-756fff0d6295.png)

**Comment by sing1ee** [comment]
我更新了，7.17.x和8.4.1分支，可以试试
