### ISSUE TITLE
当IndexOptions设置为Offsets时，索引的时候出现错误

### ISSUE THREAD

**Issue by dengzz** [sing1ee/elasticsearch-jieba-plugin#9]
reason=startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=74,endOffset=78,lastStartOffset=76 for field 'content'

**Comment by qinyuezhan** [comment]
我也出现同样的错误

**Comment by shadowinlife** [comment]
请问这个问题当前解决了木有?

**Comment by sing1ee** [comment]
还没有排出时间，抱歉。

2018-02-06 16:00 GMT+08:00 shadowinlife <notifications@github.com>:

**Comment by sing1ee** [comment]
预计年后上线。

2018-02-06 16:01 GMT+08:00 张成 <zh.milo@gmail.com>:

**Comment by shadowinlife** [comment]
谢谢~

**Comment by orangemi** [comment]
我在fork上修复了此问题，再分词后进行了一次按startOffset的排序，并且加入了测试，请大家借鉴。
https://github.com/orangemi/elasticsearch-jieba-plugin/pull/2

**Comment by sing1ee** [comment]
来个pr吧

2018-04-16 11:30 GMT+08:00 Orange Mi <notifications@github.com>:
