### ISSUE TITLE
clone分支7.17.x 使用gradle pz 命令的时候发现无法构建，最新的分支也试过了，是什么原因？

### ISSUE THREAD

**Issue by liugentlement** [sing1ee/elasticsearch-jieba-plugin#94]
这是gradle pz后错误信息：No matching configuration of project :jieba-analysis was found. The consumer was configured to find an API of a library compatible with Java 11, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally but:
          - None of the consumable configurations have attributes.

**Comment by xiehurricane** [comment]
请问是什么情况呢 我也遇到了

**Comment by edc3000** [comment]
> 请问是什么情况呢 我也遇到了

请问你后面成功打包了吗
